version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - aws --version
      - pip install pyinstaller
  build:
    commands:
      - ./remove.ps1
      - pyinstaller.exe ./test.pyw
